### ISSUE TITLE
Raspberry Pi Pico wiring diagram out of date

### ISSUE THREAD

**Issue by 0x3e** [OpenStickCommunity/Site#58]
Hello, 

The wiring diagram is missing a number of default connections

https://gp2040-ce.info/controller-build/wiring#raspberry-pi-pico 

vs 

https://github.com/OpenStickCommunity/GP2040-CE/blob/main/configs/Pico/assets/PinMapping.png
https://github.com/OpenStickCommunity/GP2040-CE/blob/main/configs/Pico/assets/PinMapping.xcf

with the OLED and TURBO being enabled by default so pins 0,1 and 15 are enabled on first install of v0.7.9. 

Caused me some issues, I had gp0 and gp1 hooked up as UART from the getting started with the pico guide and the doco did not show they would be in use and active by default.

https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf

https://imgur.com/a/pico-setup-uart-swd-from-getting-started-guide-pIH9u0Q

Happy to help out, can create a pull request later in the week.

Thank you and regards,

0x3e

**Comment by TheTrainGoes** [comment]
This was addresses a while ago, apologies on not following up sooner.
